name: Build DLL

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up MinGW
      run: |
        sudo apt-get update
        sudo apt-get install -y mingw-w64

    - name: Set up Meson and Ninja
      run: |
        sudo apt-get install -y meson ninja-build pkg-config

    - name: Set up pkg-config for MinGW
      run: |
        sudo ln -sf /usr/bin/pkg-config /usr/bin/i686-w64-mingw32-pkg-config
        sudo ln -sf /usr/bin/pkg-config /usr/bin/x86_64-w64-mingw32-pkg-config

    - name: Build for 32-bit
      env:
        PKG_CONFIG: i686-w64-mingw32-pkg-config
      run: |
        meson setup --cross cross-mingw-32.txt b32
        ninja -C b32

    - name: Build for 64-bit
      env:
        PKG_CONFIG: x86_64-w64-mingw32-pkg-config
      run: |
        meson setup --cross cross-mingw-64.txt b64
        ninja -C b64

    - name: Upload DLL artifacts
      uses: actions/upload-artifact@v3
      with:
        name: dll-artifacts
        path: |
          b32/*.dll
          b64/*.dll
