name: Build DLL

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Meson and Ninja
      run: |
        sudo apt update
        sudo apt install -y meson ninja-build

    - name: Set up MinGW
      run: |
        sudo apt install -y mingw-w64

    - name: Build 32-bit DLL
      run: |
        meson setup --cross cross-mingw-32.txt b32
        ninja -C b32

    - name: Build 64-bit DLL
      run: |
        meson setup --cross cross-mingw-64.txt b64
        ninja -C b64

    - name: Upload DLL artifacts
      uses: actions/upload-artifact@v3
      with:
        name: dlls
        path: |
          b32/*.dll
          b64/*.dll