name: Build DLL

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python (for Meson)
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y mingw-w64 ninja-build
        pip install meson

    - name: Build 32-bit DLL
      run: |
        meson setup --cross-file cross-mingw-32.txt b32
        ninja -C b32

    - name: Build 64-bit DLL
      run: |
        meson setup --cross-file cross-mingw-64.txt b64
        ninja -C b64

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: dll-builds
        path: |
          b32/*.dll
          b64/*.dll
