name: Build DLL on Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # 在 Ubuntu 上运行工作流，因为你提到的是 Linux 环境的交叉编译

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y meson ninja-build mingw-w64

      - name: Set up cross compilation for mingw32
        run: meson setup --cross cross-mingw-32.txt b32

      - name: Build with ninja for mingw32
        run: ninja -C b32

      - name: Set up cross compilation for mingw64
        run: meson setup --cross cross-mingw-64.txt b64

      - name: Build with ninja for mingw64
        run: ninja -C b64

      - name: Collect the DLL files
        run: |
          mkdir output
          cp b32/*.dll output/  # 复制 mingw32 编译的 DLL 文件
          cp b64/*.dll output/  # 复制 mingw64 编译的 DLL 文件

      - name: Upload DLL artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dll-artifacts
          path: output/