name: Build DLL

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-mingw-w64 g++-mingw-w64 meson ninja-build
        
    - name: Setup cross compilation files
      run: |
        echo '[binaries]
        c = '"'"'i686-w64-mingw32-gcc'"'"'
        cpp = '"'"'i686-w64-mingw32-g++'"'"'
        ar = '"'"'i686-w64-mingw32-ar'"'"'
        strip = '"'"'i686-w64-mingw32-strip'"'"'
        windres = '"'"'i686-w64-mingw32-windres'"'"'
        [host_machine]
        system = '"'"'windows'"'"'
        cpu_family = '"'"'x86'"'"'
        cpu = '"'"'i686'"'"'
        endian = '"'"'little'"'"'' > cross-mingw-32.txt
        
        echo '[binaries]
        c = '"'"'x86_64-w64-mingw32-gcc'"'"'
        cpp = '"'"'x86_64-w64-mingw32-g++'"'"'
        ar = '"'"'x86_64-w64-mingw32-ar'"'"'
        strip = '"'"'x86_64-w64-mingw32-strip'"'"'
        windres = '"'"'x86_64-w64-mingw32-windres'"'"'
        [host_machine]
        system = '"'"'windows'"'"'
        cpu_family = '"'"'x86_64'"'"'
        cpu = '"'"'x86_64'"'"'
        endian = '"'"'little'"'"'' > cross-mingw-64.txt

    - name: Build 32-bit DLL
      run: |
        meson setup --cross cross-mingw-32.txt b32
        ninja -C b32
        
    - name: Build 64-bit DLL
      run: |
        meson setup --cross cross-mingw-64.txt b64
        ninja -C b64

    - name: Upload 32-bit artifacts
      uses: actions/upload-artifact@v3
      with:
        name: aimeio-32bit
        path: b32/*.dll
        
    - name: Upload 64-bit artifacts
      uses: actions/upload-artifact@v3
      with:
        name: aimeio-64bit
        path: b64/*.dll
