name: Build DLL

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 检出代码
    - name: Checkout code
      uses: actions/checkout@v3

    # 安装构建工具和依赖
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ninja-build meson mingw-w64 pkg-config libssl-dev

    # 配置和编译
    - name: Configure and build (64-bit)
      run: |
        meson setup --cross-file cross-mingw-64.txt build
        ninja -C build

    # 上传生成的 DLL 文件作为构建产物
    - name: Upload DLL
      uses: actions/upload-artifact@v3
      with:
        name: compiled-dll
        path: build/